//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentSubjects = new HashSet<StudentSubjects>();
        }
    
        public int studentId { get; set; }
        public Nullable<int> levelId { get; set; }
        public decimal nationalId { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string middelName { get; set; }
        public string lastName { get; set; }
        public string surName { get; set; }
        public Nullable<int> dept_Id { get; set; }
        public Nullable<int> genderId { get; set; }
        public string image { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSubjects> StudentSubjects { get; set; }
    }
}
